import fs from "node:fs";
import path from "node:path";
import {
  acceptRisk,
  blue,
  bold,
  dim,
  findWaste,
  green,
  modelLabel,
  priceFor,
  projectionDays,
  readVerification,
  red,
  resolveVerification,
  setStatus,
  simulate,
  tokens as fmtTokens,
  toRecommendations,
  usd,
  verificationModeOf,
  wrap as wrapText,
  yellow,
} from "@optimaizr/core";
import { logVerification } from "@optimaizr/local";
import type { Args } from "../args.js";
import { load } from "../data.js";

/**
 * `optimaizr apply`: turn a verified finding into a concrete change, written to
 * `optimaizr-change.md`. It never edits your code.
 */
export async function cmdApply(args: Args): Promise<void> {
  const ruleName = args.positional[0];
  if (!ruleName) {
    console.log(`  ${red("usage:")} optimaizr apply <rule> ${dim("[--accept-risk]")}`);
    process.exitCode = 1;
    return;
  }

  const data = await load(args);
  const finding = findWaste(data).find((f) => f.rule === ruleName);
  if (!finding) {
    console.log(`  ${red("No such finding:")} ${ruleName}`);
    process.exitCode = 1;
    return;
  }

  // The gate, resolved by the same function `verify` uses so they can't disagree.
  if (args.flags["accept-risk"] && verificationModeOf(finding) === "manual") {
    // Logged as well as stored: a manual sign-off belongs in the audit trail.
    logVerification(acceptRisk(ruleName, "Accepted via 'apply --accept-risk'."));
  }

  const resolved = resolveVerification(finding, readVerification(ruleName));

  if (!resolved.canApply) {
    console.log("");
    console.log(`  ${red(resolved.state)} ${bold(finding.title)}`);
    console.log("");
    for (const line of wrapText(resolved.headline, 70)) console.log(`  ${dim(line)}`);
    if (resolved.guidance) {
      console.log("");
      for (const line of wrapText(resolved.guidance, 70)) console.log(`  ${dim(line)}`);
    }
    console.log("");
    console.log(
      `    ${blue(`optimaizr verify ${ruleName}`)}${resolved.mode === "manual" ? dim("   (explains why no replay can settle this)") : ""}`,
    );
    console.log("");
    process.exitCode = 1;
    return;
  }

  console.log("");
  console.log(`  ${green(resolved.state)} ${dim(resolved.headline)}`);

  // Say so when `--accept-risk` had nothing to accept.
  if (args.flags["accept-risk"] && resolved.mode !== "manual") {
    console.log(
      `  ${dim(`--accept-risk ignored: this finding is ${resolved.state}, so there is no risk to accept.`)}`,
    );
  }

  console.log("");
  console.log(`  ${bold(finding.title)}`);
  console.log(
    `  ${green(`${usd(finding.savings.monthlyUsd)}/mo`)} ${dim("estimated,")} ${green(usd(finding.savings.annualUsd))}${dim("/yr")}`,
  );
  console.log("");
  console.log(`  ${bold("The change")}`);
  for (const line of wrapText(finding.fix, 68)) console.log(`    ${line}`);
  console.log("");

  if (finding.candidate?.kind === "swap-model" && finding.candidate.to) {
    const target = priceFor(finding.candidate.to);
    console.log(`  ${bold("Concretely")}`);
    console.log(`    ${dim("For calls matching this profile, set:")}`);
    console.log(
      `      ${blue(`model: "${finding.candidate.to}"`)}   ${dim(`(${target?.label ?? ""})`)}`,
    );
    console.log(
      `    ${dim(`Cap max_tokens at ${target?.maxOutputTokens.toLocaleString()} for this model.`)}`,
    );
    console.log("");
  }

  const outPath = path.resolve(process.cwd(), "optimaizr-change.md");
  const doc = [
    `# ${finding.title}`,
    "",
    `**Estimated saving:** ${usd(finding.savings.monthlyUsd)}/month, ${usd(finding.savings.annualUsd)}/year`,
    `**Confidence in the figure:** ${finding.savings.confidence} - ${finding.savings.confidenceBasis}`,
    `**Quality impact:** ${finding.impact}`,
    `**Affected:** ${finding.affected.calls} calls across ${finding.affected.models.join(", ")}`,
    "",
    "## What is happening",
    "",
    finding.detail,
    "",
    "## The change",
    "",
    finding.fix,
    "",
    "## How the number was calculated",
    "",
    finding.savings.calculation,
    "",
    "## Assumptions",
    "",
    ...finding.savings.assumptions.map((a: string) => `- ${a}`),
    "",
    "## Evidence",
    "",
    ...finding.observations.map((e: string) => `- ${e}`),
    "",
    "---",
    "",
    "_Estimates, not guarantees. Generated by optimAIzr._",
  ].join("\n");

  fs.writeFileSync(outPath, doc);
  console.log(`  ${green("Written")} ${dim(outPath)}`);
  console.log(
    `  ${dim("optimAIzr does not edit your code - review the change and apply it yourself.")}`,
  );
  console.log("");
}

/** `optimaizr show <rule>`: the requests a recommendation would touch. */
export async function cmdShow(args: Args): Promise<void> {
  const ruleName = args.positional[0];
  if (!ruleName) {
    console.log(`  ${red("usage:")} optimaizr show <rule>`);
    process.exitCode = 1;
    return;
  }

  const data = await load(args);
  const finding = findWaste(data).find((f) => f.rule === ruleName);
  if (!finding) {
    console.log(`  ${red("No such finding:")} ${ruleName}`);
    process.exitCode = 1;
    return;
  }

  // Every finding names its own traffic (`sampleEventIds` is capped at 20).
  const matched = data.events.filter(finding.affects);
  const shown = [...matched].sort((a, b) => b.cost.total - a.cost.total).slice(0, 20);

  if (args.flags.json) {
    console.log(JSON.stringify(shown, null, 2));
    return;
  }

  console.log("");
  console.log(`  ${bold("optimAIzr")} ${dim("|")} requests affected by ${bold(ruleName)}`);
  console.log("");
  console.log(
    `  ${matched.length.toLocaleString()} matching requests${matched.length > shown.length ? dim(` (showing the ${shown.length} priciest)`) : ""}`,
  );
  console.log("");
  for (const e of shown) {
    const where = (e.route ?? e.project.split("/").slice(-1)[0] ?? "").slice(0, 22);
    console.log(
      `    ${usd(e.cost.total).padStart(9)} ${dim("|")} ${modelLabel(e.model).padEnd(12)} ${dim(`${fmtTokens(e.inputTokens + e.cacheReadTokens)} in / ${e.outputTokens} out`.padEnd(22))} ${dim(where.padEnd(22))} ${dim(e.ts.slice(0, 16).replace("T", " "))}`,
    );
  }
  console.log("");
  setStatus(ruleName, "viewed");
}

/**
 * `optimaizr simulate <rule>`: what the change would cost, from recorded
 * tokens. Says nothing about output quality; that's `verify`.
 */
export async function cmdSimulate(args: Args): Promise<void> {
  const ruleName = args.positional[0];
  if (!ruleName) {
    console.log(`  ${red("usage:")} optimaizr simulate <rule>`);
    process.exitCode = 1;
    return;
  }

  const data = await load(args);
  const findings = findWaste(data);
  const finding = findings.find((f) => f.rule === ruleName);
  if (!finding) {
    console.log(`  ${red("No such finding:")} ${ruleName}`);
    process.exitCode = 1;
    return;
  }

  const rec = toRecommendations(findings, data.events.length).find((r) => r.id === ruleName);
  if (!rec) {
    console.log("");
    console.log(`  ${yellow("That finding is an advisory - there is nothing to simulate.")}`);
    console.log("");
    return;
  }

  const sim = simulate(rec, finding, data.events, projectionDays(data));
  if (args.flags.json) {
    console.log(JSON.stringify(sim, null, 2));
    return;
  }

  console.log("");
  console.log(`  ${bold("optimAIzr")} ${dim("| simulation")}`);
  console.log("");
  console.log(`  ${bold(sim.action)}`);
  console.log("");
  console.log(
    `  ${dim("matched")}      ${sim.matchedCalls.toLocaleString()} requests in the window`,
  );
  if (sim.stale) {
    // Figures with no traffic under them aren't a result, so say so first.
    console.log(
      `  ${red("no matching traffic")} ${dim("- the figures below come from the finding, not from this window")}`,
    );
  }
  console.log(
    `  ${dim("window")}       ${usd(sim.currentUsd)} ${dim("->")} ${usd(sim.simulatedUsd)}`,
  );
  console.log(
    `  ${dim("projected")}    ${green(`${usd(sim.monthlySaving)}/month`)} ${dim("|")} ${green(`${usd(sim.annualSaving)}/year`)}`,
  );
  console.log("");
  if (sim.shifts.length) {
    console.log(`  ${bold("Per model")}`);
    for (const sh of sim.shifts) {
      console.log(
        `    ${modelLabel(sh.model).padEnd(14)} ${dim(`${sh.calls} calls`.padEnd(12))} ${usd(sh.from)} ${dim("->")} ${usd(sh.to)}`,
      );
    }
    console.log("");
  }
  for (const line of wrapText(sim.caveat, 68)) console.log(`  ${yellow(line)}`);
  console.log("");
  setStatus(ruleName, "simulated");
  if (sim.stale) process.exitCode = 1;
}
