// Generated by apps/cli/scripts/mod-prices.mjs from the engine's catalogue.
// Don't edit by hand: run `npm run mod:prices` in apps/cli.

export type Price = {
  label: string;
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
};

/** USD per million tokens, the rates in force when this file was written. */
export const PRICES: Record<string, Price> = {
  "claude-fable-5-1": {
    label: "Fable 5.1",
    input: 10,
    output: 50,
    cacheRead: 0.25,
    cacheWrite: 12.5,
  },
  "claude-mythos-5-1": {
    label: "Mythos 5.1",
    input: 10,
    output: 50,
    cacheRead: 0.25,
    cacheWrite: 12.5,
  },
  "claude-fable-5": { label: "Fable 5", input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 },
  "claude-mythos-5": { label: "Mythos 5", input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 },
  "claude-opus-5-5": { label: "Opus 5.5", input: 4, output: 20, cacheRead: 0.2, cacheWrite: 5 },
  "claude-opus-5": { label: "Opus 5", input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
  "claude-opus-4-8": { label: "Opus 4.8", input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
  "claude-opus-4-7": { label: "Opus 4.7", input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
  "claude-opus-4-6": { label: "Opus 4.6", input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
  "claude-sonnet-5-5": {
    label: "Sonnet 5.5",
    input: 2,
    output: 10,
    cacheRead: 0.2,
    cacheWrite: 2.5,
  },
  "claude-sonnet-5": { label: "Sonnet 5", input: 2, output: 10, cacheRead: 0.2, cacheWrite: 2.5 },
  "claude-sonnet-4-6": {
    label: "Sonnet 4.6",
    input: 3,
    output: 15,
    cacheRead: 0.3,
    cacheWrite: 3.75,
  },
  "claude-haiku-4-5": { label: "Haiku 4.5", input: 1, output: 5, cacheRead: 0.1, cacheWrite: 1.25 },
};
