// Writes the Claude Code mod's price table from the engine's catalogue. The mod
// can't import the engine, and a test fails when the two drift apart, so run
// `npm run mod:prices` in apps/cli after a price changes.

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import { MODELS, ratesFor } from "@optimaizr/core";

export const PRICES_FILE = fileURLToPath(
  new URL("../../../mods/optimaizr/hooks/prices.ts", import.meta.url),
);

/** The table as TypeScript: Claude models only, current rates, USD per million tokens. */
export function renderPrices() {
  const rows = MODELS.filter((m) => m.provider === "anthropic").map((m) => {
    const r = ratesFor(m, {});
    const n = (x) => Number(x.toFixed(4));
    return `  "${m.id}": { label: "${m.label}", input: ${n(r.inputPerM)}, output: ${n(r.outputPerM)}, cacheRead: ${n(r.cachedInputPerM)}, cacheWrite: ${n(r.cacheWrite5mPerM)}, cacheWrite1h: ${n(r.cacheWrite1hPerM)} },`;
  });
  return [
    "// Generated by apps/cli/scripts/mod-prices.mjs from the engine's catalogue.",
    "// Don't edit by hand: run `npm run mod:prices` in apps/cli.",
    "",
    "export type Price = {",
    "  label: string;",
    "  input: number;",
    "  output: number;",
    "  cacheRead: number;",
    "  cacheWrite: number;",
    "  cacheWrite1h: number;",
    "};",
    "",
    "/** USD per million tokens, the rates in force when this file was written. */",
    "export const PRICES: Record<string, Price> = {",
    ...rows,
    "};",
    "",
  ].join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await writeFile(PRICES_FILE, renderPrices());
  console.log(`wrote ${PRICES_FILE}`);
}
