import { test } from "node:test";
import assert from "node:assert/strict";

import {
  buildTasks,
  consumeCodexLine,
  createCodexState,
  findWaste,
  isReadOnlyCommand,
} from "@optimaizr/core";
import "@optimaizr/local";
import {
  bash,
  edit,
  load,
  lookup,
  OPUS,
  read,
  START,
  transcript,
} from "./fixtures/transcripts.mjs";

/**
 * Agent calls are grouped into tasks (one prompt and everything it set off) and
 * the rules judge the task: a quick lookup is cheap work, one step of a long
 * debugging session is not, though both calls look the same.
 */

/* ------------------------------------------------------------------ *
 * Grouping
 * ------------------------------------------------------------------ */

test("a prompt starts a task; tool results, meta records and injected text do not", async () => {
  const data = await load({
    s1: transcript("s1", [
      { prompt: "fix it" },
      { tools: [read("/w/a.ts")] },
      { prompt: "<system-reminder>context</system-reminder>" },
      { prompt: "Caveat: generated by local commands", meta: true },
      { tools: [edit("/w/a.ts")] },
      { out: 100 },
      { prompt: "now the other one" },
      { out: 100 },
    ]),
  });
  const tasks = buildTasks(data.events);
  assert.equal(tasks.length, 2);
  assert.equal(tasks[0].calls, 3);
  assert.equal(tasks[0].kind, "quick-edit");
  assert.equal(tasks[1].kind, "conversation");
});

test("a subagent is its own task and its own thread", async () => {
  const data = await load({
    s1: transcript("s1", [
      { prompt: "look into it" },
      { tools: [{ name: "Task", input: { prompt: "search" } }] },
      { prompt: "search", side: "ag1" },
      { tools: [read("/w/a.ts")], side: "ag1" },
      { out: 100, side: "ag1" },
      { out: 200 },
    ]),
  });
  const tasks = buildTasks(data.events);
  const sub = tasks.find((t) => t.isSubagent);
  const main = tasks.find((t) => !t.isSubagent);
  assert.equal(sub.calls, 2);
  assert.equal(sub.kind, "lookup");
  assert.equal(main.calls, 2, "the main thread's reply joins its own task, not the subagent's");
  assert.equal(main.kind, "multi-step", "delegating is more than a quick job");
});

test("compaction is recorded so later reads are fresh", async () => {
  const data = await load({
    s1: transcript("s1", [
      { prompt: "go" },
      { out: 10 },
      { compact: true },
      { prompt: "again" },
      { out: 10 },
    ]),
  });
  assert.deepEqual(
    data.events.map((e) => e.contextEpoch ?? 0),
    [0, 1],
  );
});

test("task kinds come from shape: calls, files, failures, thinking, answer length", () => {
  const ev = (turnId, i, o = {}) => ({
    id: `${turnId}-${i}`,
    source: "claude-code",
    provider: "anthropic",
    ts: new Date(START + i * 1000).toISOString(),
    model: OPUS,
    sessionId: "s",
    project: "/w",
    turnId,
    inputTokens: 10,
    outputTokens: o.out ?? 100,
    thinkingTokens: o.think ?? 0,
    cacheReadTokens: 1000,
    cacheWrite5mTokens: 0,
    cacheWrite1hTokens: 0,
    stopReason: o.stop ?? "end_turn",
    tools: o.tools ?? [],
    cost: { total: 0.01 },
  });
  const t = (name) => ({ id: name, name, signature: `${name}:x` });
  const kindOf = (events) => buildTasks(events)[0].kind;

  assert.equal(kindOf([ev("a", 0, { tools: [t("Read")] }), ev("a", 1)]), "lookup");
  assert.equal(
    kindOf(Array.from({ length: 10 }, (_, i) => ev("b", i, { tools: [t("Read")] }))),
    "multi-step",
  );
  assert.equal(
    kindOf([
      ev("c", 0, { tools: [{ ...t("Bash"), isError: true }] }),
      ev("c", 1, { tools: [{ ...t("Bash"), isError: true }] }),
    ]),
    "debugging",
  );
  assert.equal(kindOf([ev("d", 0, { tools: [t("Read")], think: 2500 })]), "reasoning");
  assert.equal(
    kindOf([ev("e", 0, { tools: [t("Read")] }), ev("e", 1, { out: 2000 })]),
    "multi-step",
  );
  // A little thinking before a step is normal and does not make it reasoning.
  assert.equal(kindOf([ev("f", 0, { tools: [t("Read")], think: 300 })]), "lookup");
});

test("a task is done when it replied, was followed, or went quiet", () => {
  const base = {
    source: "claude-code",
    provider: "anthropic",
    model: OPUS,
    sessionId: "s",
    project: "/w",
  };
  const call = (id, turnId, min, stop) => ({
    ...base,
    id,
    turnId,
    ts: new Date(START + min * 60_000).toISOString(),
    stopReason: stop,
    inputTokens: 0,
    outputTokens: 10,
    thinkingTokens: 0,
    cacheReadTokens: 0,
    cacheWrite5mTokens: 0,
    cacheWrite1hTokens: 0,
    tools: [],
    cost: { total: 0 },
  });
  const running = buildTasks([call("1", "a", 0, "tool_use")]);
  assert.equal(running[0].done, false);
  assert.equal(buildTasks([call("1", "a", 0, "end_turn")])[0].done, true);
  const followed = buildTasks([call("1", "a", 0, "tool_use"), call("2", "b", 1, "tool_use")]);
  assert.equal(followed.find((t) => t.id === "a").done, true);
  assert.equal(
    buildTasks([call("1", "a", 0, "tool_use")], { now: START + 20 * 60_000 })[0].done,
    true,
  );
});

test("Codex prompts start tasks and a non-zero exit is a failure", () => {
  const st = createCodexState("/x/rollout.jsonl");
  const line = (type, payload) =>
    JSON.stringify({ type, timestamp: "2026-09-20T10:00:00Z", payload });
  consumeCodexLine(st, line("turn_context", { model: "gpt-5" }));
  consumeCodexLine(st, line("event_msg", { type: "user_message", message: "run tests" }));
  consumeCodexLine(
    st,
    line("response_item", {
      type: "function_call",
      call_id: "c1",
      name: "exec_command",
      arguments: '{"cmd":"npm test"}',
    }),
  );
  consumeCodexLine(
    st,
    line("response_item", {
      type: "function_call_output",
      call_id: "c1",
      output: "Process exited with code 1\nfailing",
    }),
  );
  const e = consumeCodexLine(
    st,
    line("event_msg", {
      type: "token_count",
      info: {
        total_token_usage: { total_tokens: 100 },
        last_token_usage: { input_tokens: 80, output_tokens: 20, total_tokens: 100 },
      },
    }),
  );
  assert.ok(e.turnId);
  assert.equal(e.tools[0].isError, true);
});

test("read-only commands are told apart from ones that change things", () => {
  for (const c of [
    "cd /w && git status",
    'grep -n "a\\|b" f.ts',
    "rg x > /dev/null 2>&1",
    "curl -s https://x",
  ]) {
    assert.equal(isReadOnlyCommand(c), true, c);
  }
  for (const c of [
    "npm test",
    "ls > out.txt",
    "sed -i s/a/b/ f",
    "find . -delete",
    "curl -X POST https://x",
  ]) {
    assert.equal(isReadOnlyCommand(c), false, c);
  }
});

/* ------------------------------------------------------------------ *
 * Rules
 * ------------------------------------------------------------------ */

const rule = (data, name) => findWaste(data).find((f) => f.rule === name);

test("model-fit counts quick tasks on Opus, not steps of bigger ones", async () => {
  const quick = await load({
    s1: transcript("s1", Array.from({ length: 8 }, () => lookup()).flat()),
  });
  const fit = rule(quick, "model-fit");
  assert.ok(fit, "eight quick lookups on Opus should be flagged");
  assert.match(fit.title, /8 quick tasks ran on Opus 5\.5/);
  assert.match(fit.detail, /8 lookups/);

  // The same short calls, as steps of long tasks: nothing to say.
  const longTask = () => [
    { prompt: "build the feature" },
    ...Array.from({ length: 10 }, (_, i) => ({ tools: [read(`/w/f${i}.ts`)], out: 150 })),
    { out: 300 },
  ];
  const big = await load({ s1: transcript("s1", Array.from({ length: 8 }, longTask).flat()) });
  assert.equal(rule(big, "model-fit"), undefined);
});

test("model-fit leaves out a switch whose cache reload costs more than it saves", async () => {
  // One quick task deep in a huge conversation: reloading 900K tokens into
  // Sonnet's cache dwarfs what the cheaper answer saves.
  const script = [];
  for (let i = 0; i < 6; i++) {
    script.push(
      { prompt: "big work" },
      { tools: [edit(`/w/${i}.ts`)], out: 3000, think: 3000, ctx: 900_000 },
      { out: 2000, ctx: 900_000 },
    );
    script.push(...lookup({ ctx: 900_000 }));
  }
  const data = await load({ s1: transcript("s1", script) });
  assert.equal(rule(data, "model-fit"), undefined);

  // The same lookups in subagents start empty: no reload, so they count.
  const subs = [];
  for (let i = 0; i < 6; i++) subs.push(...lookup({ side: `ag${i}`, ctx: 30_000 }));
  const fit = rule(await load({ s1: transcript("s1", subs) }), "model-fit");
  assert.ok(fit);
  assert.match(fit.detail, /6 in subagents/);
});

test("oversized context compares a small task with similar small tasks", async () => {
  const script = [];
  for (let i = 0; i < 20; i++) script.push(...lookup({ ctx: 20_000 }));
  for (let i = 0; i < 6; i++) script.push(...lookup({ ctx: 400_000 }));
  const found = rule(await load({ s1: transcript("s1", script) }), "oversized-input");
  assert.ok(found);
  assert.match(
    found.title,
    /6 small tasks started with ~400\.\dK of context; similar tasks start near 20\.\dK/,
  );

  // Long work in a big context is justified, and never compared.
  const heavy = [];
  for (let i = 0; i < 20; i++) heavy.push(...lookup({ ctx: 20_000 }));
  for (let i = 0; i < 6; i++) {
    heavy.push(
      { prompt: "refactor" },
      ...Array.from({ length: 12 }, (_, k) => ({ tools: [edit(`/w/${k}.ts`)], ctx: 400_000 })),
      { out: 200, ctx: 400_000 },
    );
  }
  assert.equal(rule(await load({ s1: transcript("s1", heavy) }), "oversized-input"), undefined);
});

test("error loops count blind retries, not fix-and-rerun", async () => {
  const fail = bash("npm test", { error: true });
  const blind = await load({
    s1: transcript("s1", [
      { prompt: "test" },
      { tools: [fail] },
      { tools: [fail] },
      { tools: [fail] },
      { tools: [fail] },
      { out: 50 },
    ]),
  });
  const loop = rule(blind, "error-loops");
  assert.ok(loop);
  assert.match(loop.title, /3 retries of a failing command with nothing changed/);
  assert.match(loop.observations[0], /npm test: 3 blind retries, up to 4 in a row/);

  const debugging = await load({
    s1: transcript("s1", [
      { prompt: "fix" },
      { tools: [fail] },
      { tools: [edit("/w/a.ts", "1")] },
      { tools: [fail] },
      { tools: [edit("/w/a.ts", "2")] },
      { tools: [fail] },
      { tools: [edit("/w/a.ts", "3")] },
      { tools: [fail] },
      { out: 50 },
    ]),
  });
  assert.equal(rule(debugging, "error-loops"), undefined);

  // Different edits to one file that each fail are not the same attempt.
  const edits = await load({
    s1: transcript("s1", [
      { prompt: "edit" },
      ...["1", "2", "3", "4"].map((c) => ({ tools: [{ ...edit("/w/a.ts", c), error: true }] })),
      { out: 50 },
    ]),
  });
  assert.equal(rule(edits, "error-loops"), undefined);
});

test("re-reads count only within one context with nothing edited in between", async () => {
  const big = { chars: 40_000 };
  const r = (file, extra) => ({ ...read(file, extra), ...big });
  const repeats = (data) => rule(data, "repeat-tool-calls")?.title ?? "none";

  const dup = await load({
    s1: transcript("s1", [
      { prompt: "x" },
      { tools: [r("/w/a.ts")] },
      { tools: [r("/w/a.ts")] },
      { out: 50 },
    ]),
  });
  assert.match(repeats(dup), /^1 redundant re-read/);

  const afterEdit = await load({
    s1: transcript("s1", [
      { prompt: "x" },
      { tools: [r("/w/a.ts")] },
      { tools: [edit("/w/a.ts")] },
      { tools: [r("/w/a.ts")] },
      { out: 50 },
    ]),
  });
  assert.equal(repeats(afterEdit), "none");

  const slices = await load({
    s1: transcript("s1", [
      { prompt: "x" },
      { tools: [r("/w/a.ts", { offset: 1, limit: 100 })] },
      { tools: [r("/w/a.ts", { offset: 101, limit: 100 })] },
      { out: 50 },
    ]),
  });
  assert.equal(repeats(slices), "none");

  const afterCompact = await load({
    s1: transcript("s1", [
      { prompt: "x" },
      { tools: [r("/w/a.ts")] },
      { out: 50 },
      { compact: true },
      { prompt: "y" },
      { tools: [r("/w/a.ts")] },
      { out: 50 },
    ]),
  });
  assert.equal(repeats(afterCompact), "none");

  const subagent = await load({
    s1: transcript("s1", [
      { prompt: "x" },
      { tools: [r("/w/a.ts")] },
      { prompt: "look", side: "ag1" },
      { tools: [r("/w/a.ts")], side: "ag1" },
      { out: 50, side: "ag1" },
      { out: 50 },
    ]),
  });
  assert.equal(repeats(subagent), "none");
});

test("oversized output ignores calls that wrote a file", async () => {
  const script = [{ prompt: "write it all" }];
  for (let i = 0; i < 24; i++)
    script.push({
      tools: [{ name: "Write", input: { file_path: `/w/${i}.ts`, content: "x" } }],
      out: 9000,
    });
  for (let i = 0; i < 24; i++) script.push({ tools: [read(`/w/r${i}.ts`)], out: 300 });
  script.push({ out: 300 });
  assert.equal(rule(await load({ s1: transcript("s1", script) }), "oversized-output"), undefined);
});
